export const Actions = {
  FETCH_OFFER: 'FETCH_OFFER',
  FETCH_OFFERS: 'FETCH_OFFERS',
  FETCH_NEAREST_OFFERS: 'FETCH_OFFERS',
  FETCH_FAVORITES_OFFERS: 'FETCH_FAVORITES_OFFERS',
  CHANGE_FAVORITE_STATUS: 'CHANGE_FAVORITE_STATUS',
  CHANGE_CITY: 'CHANGE_CITY',
  CHANGE_SORT_VARIANT: 'CHANGE_SORT_VARIANT',
  CHECK_AUTH_STATUS: 'CHECK_AUTH_STATUS',
  AUTHORIZE: 'AUTHORIZE',
  LOGOUT: 'LOGOUT',
  FETCH_OFFER_COMMENTS: 'FETCH_OFFER_COMMENTS',
  POST_OFFER_COMMENT: 'POST_OFFER_COMMENT'
};
